### ISSUE TITLE
Cannot import highlights after a certain point

### ISSUE THREAD

**Issue by wyrdash** [valeriangalliat/kobo-highlights-to-calibre#11]
I get this error when I try to import highlights:

```
Fetching highlights for: The Complete Book of the New Sun
Could not use precise highlight targeting for bookmark f388e98e-9d2f-4099-ae87-4a17cce14ed9
file:///~/kobo-highlights-to-calibre/bookmark.js:153
      length += node.nodeValue.length
                               ^

TypeError: Cannot read properties of null (reading 'length')
    at koboCfiFix (~/kobo-highlights-to-calibre/bookmark.js:153:32)
    at processBookmark (~/kobo-highlights-to-calibre/bookmark.js:264:11)
    at processChapter (~/kobo-highlights-to-calibre/chapter.js:14:24)
    at processChapter.next (<anonymous>)
    at processBook (~/kobo-highlights-to-calibre/book.js:47:22)
    at processBook.next (<anonymous>)
    at ~/kobo-highlights-to-calibre/index.js:122:20

```
I've tried reinstalling to no avail, just for due diligence.

(I inserted tildes to slightly redact the file path as I don't assume they're important, I am on windows 11 though if that matters)

Is there anything I should change about how I highlight (i.e. dont highlight the first word of a chapter)? Is there anything I can do to troubleshoot?

Thanks.

**Comment by wyrdash** [comment]
Now it just hangs on
```
Could not use precise highlight targeting for bookmark 3f8c9141-a69d-47d0-ba1b-6f548653a82a
```

and doesn't import highlights from an entire chapter. I need to open a new window to reset it

edit: sorry for closing and reopening!

**Comment by l-konrad** [comment]
same issue here
